### ISSUE TITLE
Any info on the license choice?

### ISSUE THREAD

**Issue by tony** [ASMfreaK/aiotinydb#10]
I can't use LGPL on python libraries - not due to my own sensibility fyi - it makes life complicated downstream since it makes the code incompatible with 90% of python projects from a license perspective. 

These days I am more hesitant to stray away from the standard library at all.  There's 3 reasons I can think of why I felt a bit curious:

1. tinydb itself uses MIT: https://github.com/msiemens/tinydb/blob/master/LICENSE
2. A lot of the https://github.com/aio-libs/ use permissive licenses 
3. Compare on PyPI the usage across libraries to see what other open source projects use:
  
   https://pypi.org/search/?q=&o=&c=License+%3A%3A+OSI+Approved+%3A%3A+GNU+Library+or+Lesser+General+Public+License+%28LGPL%29

   It's hard to do an "or" search, but there's about 5 different LGPL licenses on file

Is there any reason why this license used LGPL rather than the more compatible ones? was there a conversation before somewhere?

What do you think about the license?

**Comment by asmfreak** [comment]
> Is there any reason why this license used LGPL rather than the more compatible ones? was there a conversation before somewhere?

There wasn't any conversations on licensing. It was my little hobby project at the time I thought `tinydb` would be useful for my pet projects. I studied different open source licences and found LGPL to be the most suitable at the time. The library is largely unmaintained now. And maybe I should even archive it.
