### ISSUE TITLE
Reviving aiotinydb

### ISSUE THREAD

**Issue by d-k-bo** [ASMfreaK/aiotinydb#11]
Hi, according to the commit history and some comments (https://github.com/ASMfreaK/aiotinydb/issues/6#issuecomment-639076715, https://github.com/ASMfreaK/aiotinydb/issues/10#issuecomment-1077858596), this project is unmaintained.

Since TinyDB offers what I'm looking for, but I need an async interface, I'd like to revive this project.

There are currently some major problems:

- Incompatibility with TinyDB >= 4.0 (resulting in issues like https://github.com/ASMfreaK/aiotinydb/issues/9)
- Incompatibility with newer versions of aiofiles
- outdated test dependencies (like nose & rednose)
- missing support for newer packaging/installation workflows (e.g. [PEP 518](https://peps.python.org/pep-0518/) support)

I applied some changes in [aiotinydb-revived](https://github.com/d-k-bo/aiotinydb-revived):

- support TinyDb >= 4.0 (all tests passing)
- explicit support for Python 3.6-3.10 and PyPy3 (like TinyDB)
- move project metadata and configuration to the universal pyproject.toml format
- use [flit](https://flit.pypa.io/en/latest/) for easier publishing
- more accessible automation and multi-version testing using [nox](https://nox.thea.codes/en/stable/) (this could also be done using tox, but IMHO the noxfile.py format is more readable, especially when using it for both linting and testing against multiple Python versions)

What I plan to do:

- make pylint ruleset less verbose
- support https://github.com/ASMfreaK/aiotinydb/issues/6
- improve type hints
- add additional tests (the current tests already offer 100 % code coverage, but I think there are still some untested edge cases)
- use a maintained alternative to bumpversion
- maybe: use [black](https://black.readthedocs.io/en/stable/) and [isort](https://pycqa.github.io/isort/) for formatting

As far as I can tell from the issues section, you don't use this library anymore and aren't interested to work on it — correct me if I'm wrong.

If you are interested, I'm willing to maintain this project in the future.

This would require:

- clarification of the project's license
    - according to the LICENSE.md file and a comment, this library is licensed under the terms of LGPL-3.0-only
    - by contrast, the package metadata and the file headers state that it is licensed under the terms of GPL-3.0-or-later
    - I suggest keeping the LGPL and updating the file headers accordingly
- ownership transfer or granting write access for both the repo and the pypi project

If you prefer, I can also create a PR or continue as a standalone project (this would also require addressing the licensing ambiguity).

**Comment by asmfreak** [comment]
I suggest we move aiotinydb into a new namespace (`aiotinydb/aiotinydb`), whereas my "fork" (`ASMfreaK/aiotinydb`) would become archived. In this new namespace I'll give you @d-k-bo maintainer rights. I'll se what can be done about PyPI, but we can solve that thing too.

**Comment by asmfreak** [comment]
@d-k-bo Please contact me over email, so I can give you a maintainer role on PyPI.

**Comment by d-k-bo** [comment]
@ASMfreaK could you please resolve the licensing problems? If this library should be released under the terms of the LGPL, the copyright notices should include the version (3 vs. 3 or later) and "GNU General Public License" should be replaced by "GNU Lesser General Public License" (see https://www.gnu.org/licenses/gpl-howto.en.html)

**Comment by d-k-bo** [comment]
@ASMfreaK You stated in some other issues that you intended to release this library under the terms of the LGPL. Is it okay for you if I change the copyright notices to reflect this by replacing "GNU General Public License" with "GNU Lesser General Public License"?

**Comment by asmfreak** [comment]
@d-k-bo
You can change the license in all files to LGPL. We also should include the version number, as you said earlier.
Thank you for your work!
