### ISSUE TITLE
async calls should take loop as kwarg

### ISSUE THREAD

**Issue by asmfreak** [ASMfreaK/aiotinydb#5]
In a situation where there are 2 or more main loops one should be able to specify, which to use.

**Comment by d-k-bo** [comment]
The `loop` parameter [has been deprecated in Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#deprecated) and was removed in Python 3.10. I think it's not worth the effort to implement this feature for older Python versions that are EOL/only receive security fixes.
