### ISSUE TITLE
truncate does not work

### ISSUE THREAD

**Issue by Thijxx** [ASMfreaK/aiotinydb#9]
```
    async with AIOTinyDB(DATABASE) as db:
            db.truncate()
            self.logger.info(f"Truncated: {db}")
            return True
```
response:
`AttributeError: 'Table' object has no attribute 'truncate'`

there does not seem to be any table object to truncate

**Comment by d-k-bo** [comment]
Compatibility with TinyDB version 4 was implemented in #12 and this should be fixed now.
